name: crm1

services:
  app:
    build: .
    image: crm1-image:1.0
    container_name: crm1-app-container
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./project:/app/project
  
  postgres:
    image: postgres:17.5
    container_name: crm1-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2-alpine
    container_name: crm1-redis-container
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data: