# Generated by Django 5.2.3 on 2025-07-07 14:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('heard_from', models.CharField(choices=[('reference', 'Reference'), ('google', 'Google/Website'), ('advertisement', 'Advertisement'), ('events', 'Events'), ('tender', 'Tender')], default='google', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_unit', models.CharField(choices=[('acres', 'Acres'), ('cent', 'Cent')], default='acres', max_length=10)),
                ('estimate_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposal_required', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('enquired', 'Enquired'), ('business', 'Business'), ('droped', 'Droped')], default='enquired', max_length=100, null=True)),
                ('heard_from', models.CharField(choices=[('reference', 'Reference'), ('google', 'Google/Website'), ('advertisement', 'Advertisement'), ('events', 'Events'), ('tender', 'Tender')], default='google', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('confirm_as_business', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('service_types', models.ManyToManyField(to='base.service')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_unit', models.CharField(choices=[('acres', 'Acres'), ('cent', 'Cent')], default='acres', max_length=10)),
                ('estimate_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('proposal_required', models.BooleanField(default=False)),
                ('site_visit_on', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
                ('service_types', models.ManyToManyField(to='base.service')),
            ],
        ),
    ]
