# Generated by Django 5.2.3 on 2025-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_work_site_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='pending', max_length=100, null=True),
        ),
    ]
