# Generated by Django 5.2.3 on 2025-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(blank=True, choices=[('enquired', 'Enquired'), ('business', 'Business'), ('dropped', 'Dropped')], default='enquired', max_length=100, null=True),
        ),
    ]
